new changes in header and in footer
QAsRevenge/devops-netonnet-g2 pull request #8
Opened 2023-08-09 17:53 UTC by Nishat7155

header, footer changed with our logo

2023-08-10 08:11 UTC, QAsRevenge requested changes
We can talk more about what the project is actually about in next week or see if we can coordinate a call with all of us this weekend. Till then and everybody is onboard lets hold off on PRs :).

2023-08-10 08:11 UTC, QAsRevenge commented on src/components/Header.jsx
> +                Get started <span className="hidden lg:inline"></span>
Span no longer needed since its empy ;)

2023-08-10 08:11 UTC, QAsRevenge commented on src/components/Footer.jsx
Lots of confusion about what the project is actually about but were not creating a new NetOnNet site so we shouldnt be using their name on our website. To my understanding were creating an internal 'dashboard' for us as a DevOps team, called Noffnet, following the practices of NetOnNet. We can talk more about this and really get going next week :)!.

2023-08-10 08:11 UTC, QAsRevenge commented on src/images/logo.jpg
Better to use SVGs for more consistent resolution across screens. A quick trick is to import the jpg into Figma and from there export it as a SVG!

2023-08-15 13:01 UTC, closed without merging

2023-08-15 15:14 UTC, nishat-jahan-lisa commented on src/images/logo.jpg
ok but we will use the logo which you made, and sure we will export it as SVG